AutoBookRelease/Controllers/BookController.cs
using AB.Business;
using AB.Core.Domain;
using AutoBookRelease.Models;
using System.Web.Mvc;
using System.Linq;
using System.Linq.Expressions;
using System.Collections.Generic;
using AB.Business.Interfaces;
using System;

namespace AutoBookRelease.Controllers
{
    public class BookController : Controller
    {
        private IGenericController<Book> genericControlerBook;
        private IGenericController<GiveOutBook> genericControllerGiveOutBook;
        private IGenericController<Reader> genericControllerReader;
        private IGiveOutBooksController giveOutBooksController;

        public BookController(
            IGenericController<Book> _iocBookController,
            IGenericController<Reader> _iocReaderController,
            IGenericController<GiveOutBook> _iocGiveOutBookController,
            IGiveOutBooksController _giveOutBooksController)
        {
            genericControlerBook = _iocBookController ?? throw new Exception("_iocBookController is null");
            genericControllerGiveOutBook = _iocGiveOutBookController ?? throw new Exception("_iocGiveOutBookController is null");
            genericControllerReader = _iocReaderController ?? throw new Exception("_iocReaderController is null");
            giveOutBooksController = _giveOutBooksController ?? throw new Exception("_giveOutBooksController is null");
        }

        public ActionResult Index()
        {
            return View(genericControlerBook.Get());
        }

        public ActionResult Add()
        {
            return View();
        }
        public ActionResult Update(int bookId)
        {
            Book book = genericControlerBook.Get(x => x.Id == bookId).FirstOrDefault();
            return View((BookModel)book);
        }

        public ActionResult AddBook(BookModel model)
        {
            ViewBag.addResult = genericControlerBook.Cretate((Book)model);
            return View("~/Views/Book/Add.cshtml");
        }
        public ActionResult UpdateBook(BookModel model)
        {
            ViewBag.updateResult = genericControlerBook.Update((Book)model);
            return View("~/Views/Book/Update.cshtml", model);
        }
        public ActionResult DeleteBook(int bookId)
        {
            genericControlerBook.Delete(bookId);
            return View("~/Views/Book/Index.cshtml", genericControlerBook.Get());
        }

        public ActionResult SearchBook(string bookName)
        {
            return View("~/Views/Book/Index.cshtml",
                string.IsNullOrEmpty(bookName) ?
                genericControlerBook.Get() :
                genericControlerBook.Get(x => x.Name.Equals(bookName))
                );
        }

        public ActionResult GiveOutBooks()
        {
            SetGiveOutViewBagData();
            return View();
        }
        public ActionResult GiveOutBookAction(GiveOutBookModel model)
        {
            ViewBag.giveOutResult = genericControllerGiveOutBook.Cretate((GiveOutBook)model);
            SetGiveOutViewBagData();
            return View("~/Views/Book/GiveOutBooks.cshtml");
        }
        private void SetGiveOutViewBagData()
        {
            ViewBag.Readers = genericControllerReader.Get()
                .Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() });
            ViewBag.AvailableBooks = giveOutBooksController.GetAvailableBooks()
                .Select(x => new SelectListItem() { Text = x.Name, Value = x.Id.ToString() });
            ViewBag.GivenOutBooks = giveOutBooksController.Get();
        }

    }
}

AutoBookRelease/Controllers/ReaderController.cs
using AB.Business;
using AB.Business.Interfaces;
using AB.Core.Domain;
using AutoBookRelease.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace AutoBookRelease.Controllers
{
    public class ReaderController : Controller
    {
        private IGenericController<Reader> genericControllerReader;

        public ReaderController(IGenericController<Reader> _iocReaderController)
        {
            genericControllerReader = _iocReaderController ?? throw new Exception("_iocReaderController is null");
        }

        public ActionResult Index()
        {
            return View(genericControllerReader.Get());
        }

        public ActionResult Add(BookModel model)
        {
            return View();
        }
        public ActionResult Update(int readerId)
        {
            Reader reader = genericControllerReader.Get(x => x.Id == readerId).FirstOrDefault();
            return View((ReaderModel)reader);
        }

        public ActionResult AddReader(ReaderModel model)
        {
            ViewBag.addResult = genericControllerReader.Cretate((Reader)model);
            return View("~/Views/Reader/Add.cshtml");
        }
        public ActionResult UpdateReader(ReaderModel model)
        {
            ViewBag.updateResult = genericControllerReader.Update((Reader)model);
            return View("~/Views/Reader/Update.cshtml", model);
        }
        public ActionResult DeleteReader(int readerId)
        {
            genericControllerReader.Delete(readerId);
            return View("~/Views/Reader/Index.cshtml", genericControllerReader.Get());
        }

        public ActionResult SearchReader(string readerName)
        {
            return View("~/Views/Reader/Index.cshtml",
                string.IsNullOrEmpty(readerName) ?
                genericControllerReader.Get() :
                genericControllerReader.Get(x => x.Name.Equals(readerName))
                );
        }
    }
}

AutoBookRelease/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/moment.js")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div style="width:20%; float:left; text-align:center; margin-top:3px; color:white">
                <b>Автоматизированное Рабочее Место Библиотекаря</b>
            </div>
            <div class="navbar-collapse collapse" style="float:left">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Книги", "Index", "Book")</li>
                    <li>@Html.ActionLink("Читатели", "Index", "Reader")</li>
                    <li>@Html.ActionLink("Выданные книги", "GiveOutBooks", "Book")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer></footer>
    </div>


</body>
</html>